name: sanhour_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.2.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  fl_chart: ^0.67.0
  file_picker: ^8.0.3
  excel: ^2.1.0
  url_launcher: ^6.3.0
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1
  firebase_core: ^3.1.1
  firebase_analytics: ^11.1.1
  firebase_messaging: ^15.0.2
  hive_flutter: ^1.1.0
  logger: ^2.4.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  timezone: ^0.9.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
